package com.itsaky.androidide.idetooltips

object TooltipTag {
	const val BUILD_VARIANT_SIDEBAR = "project.sidebar.buildvariants"
	const val CLOSE_PROJECT_SIDEBAR = "project.sidebar.closeproject"
	const val FILE_TREE_SIDEBAR = "project.sidebar.filetree"
	const val HELP_SIDEBAR = "project.help"
	const val PREFERENCES_SIDEBAR = "main.prefs"
	const val TERMINAL_SIDEBAR = "project.sidebar.terminal"
	const val EDITOR_TOOLBAR_CODE_ACTIONS = "editor.toolbar.codeactions"
	const val EDITOR_TOOLBAR_COPY = "editor.toolbar.copy"
	const val EDITOR_TOOLBAR_OUTPUT_COPY = "output.selection.copy"
	const val EDITOR_TOOLBAR_CUT = "editor.toolbar.cut"
	const val EDITOR_TOOLBAR_EXPAND_SELECTION = "editor.toolbar.expandselect"
	const val EDITOR_TOOLBAR_LONG_SELECT = "editor.toolbar.longselect"
	const val EDITOR_TOOLBAR_PASTE = "editor.toolbar.paste"
	const val EDITOR_TOOLBAR_SELECT_ALL = "editor.toolbar.selectall"
	const val EDITOR_TOOLBAR_OUTPUT_SELECT_ALL = "output.selection.selectall"
  const val EDITOR_TOOLBAR_FORMAT_CODE = "editor.toolbar.formatcode"
	const val EDITOR_TOOLBAR_HELP = "editor.toolbar.help"
	const val EDITOR_TOOLBAR_AI = "editor.toolbar.ai"
	const val PROJECT_APP_LOGS = "project.applogs"
	const val PROJECT_IDE_LOGS = "project.idelogs"
	const val PROJECT_SEARCH_RESULTS = "project.searchresults"
	const val PROJECT_DIAGNOSTICS = "project.diagnostics"
    const val PROJECT_AGENT = "project.agent"
	const val OUTPUT_CLEAR = "output.clear"
	const val OUTPUT_SHARE_EXTERNAL = "output.share.external"
	const val PROJECT_BUILD_OUTPUT = "project.buildoutput"
	const val PROJECT_GRADLE_TASKS = "project.gradle.tasks"
    const val PROJECT_RUN_GRADLE_TASKS = "project.run.gradle.tasks"

    // General Preferences
    const val PREFS_TOP = "prefs.top"
    const val PREFS_EDITOR = "prefs.editor"
    const val PREFS_GENERAL = "prefs.general"
    const val PREFS_BUILD_RUN = "prefs.buildrun"
    const val PREFS_GRADLE = "prefs.gradle"
    const val PREFS_TERMUX = "prefs.termux"
    const val PREFS_EDITOR_XML = "prefs.editor.xml"
    const val PREFS_DEVELOPER = "prefs.developer"
    const val PLUGIN_MANAGER = "plugin.manager"
    const val TEMPLATE_TABBED_ACTIVITY = "template.tabbed.activity"
    const val TEMPLATE_LEGACY_PROJECT = "template.legacy.project"
    const val TEMPLATE_EMPTY_ACTIVITY = "template.empty.activity"
    const val TEMPLATE_BOTTOM_NAV_ACTIVITY = "template.bottomnav.activity"
    const val TEMPLATE_COMPOSE_ACTIVITY = "template.compose.activity"
    const val TEMPLATE_BASIC_ACTIVITY = "template.basic.activity"
    const val TEMPLATE_NO_ACTIVITY = "template.no.activity"
    const val TEMPLATE_NAV_DRAWER_ACTIVITY = "template.navdrawer.activity"
    const val TEMPLATE_NDK_ACTIVITY = "template.ndk.activity"

    // Editor screen
    const val EDITOR_PROJECT_OVERVIEW = "project.overview"
    const val EDITOR_BUILD_STATUS = "project.status"

    // Code Actions menu
    const val EDITOR_CODE_ACTIONS_COMMENT = "editor.codeactions.comment"
    const val EDITOR_CODE_ACTIONS_UNCOMMENT = "editor.codeactions.uncomment"
    const val EDITOR_CODE_ACTIONS_GOTO_DEF = "editor.codeactions.gotodef"
    const val EDITOR_CODE_ACTIONS_FIND_REFS = "editor.codeactions.findrefs"
    const val EDITOR_CODE_ACTIONS_FIX_IMPORTS = "editor.codeactions.fiximports"
    const val EDITOR_CODE_ACTIONS_SETTER_GETTER = "editor.codeactions.settergetter"
    const val EDITOR_CODE_ACTIONS_SETTER_GETTER_DIALOG = "editor.codeactions.settergetter.dialog"
    const val EDITOR_CODE_ACTIONS_OVERRIDE_SUPER = "editor.codeactions.overridesuper"
    const val EDITOR_CODE_ACTIONS_OVERRIDE_SUPER_DIALOG = "editor.codeactions.overridesuper.dialog"
    const val EDITOR_CODE_ACTIONS_GEN_CONSTRUCTOR = "editor.codeactions.genconstructor"
    const val EDITOR_CODE_ACTIONS_GEN_CONSTRUCTOR_DIALOG = "editor.codeactions.genconstructor.dialog"
    const val EDITOR_CODE_ACTIONS_GEN_TO_STRING = "editor.codeactions.gentostring"
    const val EDITOR_CODE_ACTIONS_GEN_TO_STRING_DIALOG = "editor.codeactions.gentostring.dialog"
    const val EDITOR_CODE_ACTIONS_UNUSED_IMPORTS = "editor.codeactions.unusedimports"
    const val EDITOR_CODE_ACTIONS_ORGANIZE_IMPORTS = "editor.codeactions.organizeimports"

    const val EXIT_TO_MAIN = "exit.to.main"

    // Main Page
    const val MAIN_GET_STARTED = "main.get.started"
    const val PROJECT_OPEN = "project.open"
    const val MAIN_PROJECT_DELETE = "main.project.delete"
    const val MAIN_HELP = "main.help"
    const val FEEDBACK = "feedback"
    const val MAIN_PREFERENCES = "main.prefs"
    const val MAIN_TERMINAL = "main.terminal"
    const val MAIN_GIT = "main.git"

    // Editor toolbar
    const val EDITOR_TOOLBAR_NAV_ICON = "project.menu"
    const val EDITOR_TOOLBAR_QUICK_RUN = "project.run"
    const val EDITOR_TOOLBAR_DEBUG = "project.debug"
    const val EDITOR_TOOLBAR_FIND = "project.find.top"
    const val EDITOR_TOOLBAR_FIND_IN_PROJECT = "project.find.in.project"
    const val EDITOR_TOOLBAR_FIND_IN_FILE = "editor.find.in.file"
    const val EDITOR_TOOLBAR_SYNC = "project.sync"
    const val EDITOR_TOOLBAR_LAUNCH_APP = "project.launch.app"
    const val EDITOR_TOOLBAR_UNDO = "editor.undo"
    const val EDITOR_TOOLBAR_REDO = "editor.redo"
    const val EDITOR_TOOLBAR_QUICK_SAVE = "project.save"
    const val EDITOR_TOOLBAR_PREVIEW_LAYOUT = "editor.layout.preview"
    const val EDITOR_TOOLBAR_PREVIEW_COMPOSE = "editor.compose.preview"
    const val EDITOR_TOOLBAR_COMPUTER_VISION = "project.layout.vision"
    const val EDITOR_TOOLBAR_LOG_SENDER = "editor.disconnect.logsenders"

    // Floating window chrome
    const val WINDOW_MINIMIZE = "window-min"
    const val WINDOW_MAXIMIZE = "window-max"
    const val WINDOW_DOCK = "window-dock"
    const val WINDOW_UNDOCK = "window-undock"

    // Delete project
    const val DELETE_PROJECT = "project.delete"
    const val DELETE_PROJECT_SELECT = "project.delete.select"
    const val DELETE_PROJECT_BUTTON = "project.delete.button"
    const val DELETE_PROJECT_CONFIRM = "project.delete.confirm"
    const val DELETE_PROJECT_DIALOG = "project.delete.dialog"


    const val PROJECT_NEW = "project.new"
	const val PROJECT_RECENT_TOP = "project.recent.top"
	const val PROJECT_INFO_TOOLTIP = "project.recent.info"
	const val PROJECT_RECENT_RENAME = "project.recent.rename"
	const val PROJECT_OPEN_FOLDER = "project.open.folder"

    const val PROJECT_ITEM_COPYPATH = "project.item.copypath"
    const val PROJECT_ITEM_DELETE = "project.item.delete"
    const val PROJECT_CONFIRM_DELETE = "project.confirm.delete"
    const val PROJECT_FOLDER_NEWFILE = "project.folder.newfile"
    const val PROJECT_FOLDER_NEW_FOLDER = "project.folder.newfolder"
    const val PROJECT_NEWFILE_DIALOG = "project.newfile.dialog"
    const val PROJECT_FOLDER_NEWTYPE = "project.folder.newtype"
    const val PROJECT_FOLDER_NEWXML = "project.folder.newxml"
    const val PROJECT_ITEM_RENAME = "project.item.rename"
    const val PROJECT_RENAME_DIALOG = "project.rename.dialog"
    const val PROJECT_NEW_FOLDER_DIALOG = "project.newfolder.dialog"
    const val PROJECT_FOLDER_HELP = "project.folder.help"
    const val PROJECT_FILE_OPENWITH = "project.file.openwith"

    // Template Details
    const val SETUP_PREVIOUS = "setup.previous"
    const val SETUP_OVERVIEW = "setup.overview"
	const val SETUP_CREATE_PROJECT = "setup.create.project"

    // Debugger
    const val PROJECT_DEBUGGER_OUTPUT = "project.debugger.output"
    const val DEBUG_THREAD_SELECTOR = "debug.thread.selector"
    const val DEBUG_OUTPUT_VARIABLES = "debug.output.variables"
    const val DEBUG_OUTPUT_CALLSTACK = "debug.output.callstack"
    const val DEBUG_NOT_CONNECTED = "debug.not.connected"
    const val DEBUG_THREAD_SELECT_DIALOG = "debug.thread.select.dialog"
    const val EDITOR_CHARACTER_TOOLBAR = "editor.character.toolbar"

    const val DIALOG_FIND_IN_PROJECT = "project.find.dialog"
    const val DIALOG_FIND_IN_FILE = "file.find.dialog"
    const val DIALOG_FIND_IN_FILE_OPTIONS = "file.find.options"
    const val DIALOG_REPLACE_IN_FILE = "file.find.replace.dialog"
    const val PROJECT_FILENAME = "project.filename"
    const val EDITOR_FILE_CLOSE_OPTIONS = "editor.file.close.options"
    const val PROJECT_FILE_HELP = "project.file.help"

    // Debugger Actions
    const val DEBUGGER_ACTION_MOVE = "debug.toolbar.move"
    const val DEBUGGER_ACTION_PAUSE_RESUME = "debug.toolbar.pauseresume"
    const val DEBUGGER_ACTION_STEP_OVER = "debug.toolbar.stepover"
    const val DEBUGGER_ACTION_STEP_INTO = "debug.toolbar.stepinto"
    const val DEBUGGER_ACTION_STEP_OUT = "debug.toolbar.stepout"
    const val DEBUGGER_ACTION_KILL = "debug.toolbar.kill"
    const val DEBUGGER_ACTION_RESTART = "debug.toolbar.restart"

    const val PROJECT_PLUGIN_TAB = "project.plugin.tab"

    // Git
    const val GIT_DOWNLOAD_SCREEN = "git.download"
    const val GIT_PREFS = "git.prefs"
    const val PROJECT_GIT = "project.git"
    const val PROJECT_GIT_SUMMARY = "project.git.summary"
    const val PROJECT_GIT_DESCRIPTION = "project.git.description"
    const val PROJECT_GIT_FILES = "project.git.files"
    const val PROJECT_GIT_ID = "project.git.id"
    const val PROJECT_GIT_COMMIT = "project.git.commit"
    const val PROJECT_GIT_COMMIT_HISTORY = "project.git.commit.history"
    const val PROJECT_GIT_ABORT = "project.git.abort"
    const val GIT_COMMIT_HISTORY = "git.commit.history"
    const val GIT_DIALOG_SAVE = "git.dialog.save"
    const val GIT_DIALOG_MERGE_CONFLICTS = "git.dialog.mergeconflicts"
    const val GIT_DIALOG_PULL_FAIL = "git.dialog.pullfail"
    const val GIT_DIALOG_PUSH_FAIL = "git.dialog.pushfail"
    const val GIT_DIALOG_ABORT_MERGE = "git.dialog.abortmerge"
    const val GIT_PUSH = "git.action.push"
    const val GIT_PULL = "git.action.pull"
}
